"""Redis模块常量定义"""

# Redis运行模式
REDIS_MODE_EMBEDDED = 'embedded'
REDIS_MODE_EXTERNAL = 'external'

# 序列化相关常量
PICKLE_PREFIX = b'!'
SERIALIZATION_FORMAT_PICKLE = 'pickle'
SERIALIZATION_FORMAT_JSON = 'json'

# 默认配置
DEFAULT_EMBEDDED_DBFILE = None
DEFAULT_EXTERNAL_CONFIG = None

# 连接相关
DEFAULT_CONNECTION_TIMEOUT = 5
DEFAULT_SOCKET_TIMEOUT = 5

# 错误重试
MAX_RECONNECT_ATTEMPTS = 3
RECONNECT_DELAY = 1  # 秒